### ISSUE TITLE
AsUdp receiver in ST Language as Broadcast

### ISSUE THREAD

**Issue by mhdazeem** [hilch/demo-AsTcp-AsUdp#1]
Hi,

I am new to B&R Automation Studio, so, please excuse my ignorance.  I am trying to use the AsUdp Library to send the Broadcast message to find the related devices on the network. 

I am able to send the message successfully but having an issue when receiving the responses from the servers. Any help with the receiving code. 

Thanks
Azeem

**Comment by hilch** [comment]
I just found this very old open issue :-(. Think this has been solved in the meanwhile...
Unfortunately I can not support common questions via this platform and recommend to contact the local B&R office or try the new B&R community (https://community.br-automation.com/) instead. 
thanks for understanding.
